from enum import Enum

REQUEST_DELETE_CONTENT_RANGE = 'deleteContentRange'
REQUEST_DELETE_TABLE_ROW = 'deleteTableRow'
REQUEST_INSERT_TABLE = 'insertTable'
REQUEST_INSERT_TABLE_ROW = 'insertTableRow'
REQUEST_INSERT_TEXT = 'insertText'
REQUEST_MERGE_TABLE_CELLS = 'mergeTableCells'
REQUEST_UPDATE_TEXT_STYLE = 'updateTextStyle'

BOLD = 'bold'
ITALIC = 'italic'
UNDERLINE = 'underline'
STRIKETHROUGH = 'strikethrough'
SMALL_CAPS = 'smallCaps'
HEADING_ID = 'headingId'
BODY = 'body'
BOOKMARK_ID = 'bookmarkId'
CONTENT = 'content'
COLUMN_INDEX = 'columnIndex'
COLUMN_SPAN = 'columnSpan'
CONTENT = 'content'
ELEMENTS = 'elements'
END_INDEX = 'endIndex'
END_OF_SEGMENT_LOCATION = 'endOfSegmentLocation'
FIELDS = 'fields'
INDEX = 'index'
INSERT_BELOW = 'insertBelow'
LINK = 'link'
LOCATION = 'location'
NUMBER_OF_COLUMNS = 'columns'
NUMBER_OF_ROWS = 'rows'
PARAGRAPH = 'paragraph'
RANGE = 'range'
ROW_INDEX = 'rowIndex'
ROW_SPAN = 'rowSpan'
SEGMENT_ID = 'segmentId'
START_INDEX = 'startIndex'
TABLE = 'table'
TABLE_CELLS = 'tableCells'
TABLE_CELL_LOCATION = 'tableCellLocation'
TABLE_RANGE = 'tableRange'
TABLE_ROWS = 'tableRows'
TABLE_START_LOCATION = 'tableStartLocation'
TEXT = 'text'
TEXT_RUN = 'textRun'
TEXT_STYLE = 'textStyle'
URL = 'url'

class TextStyleFields(Enum):
    BOLD = 'bold'
    UNKNOWN = '*'
