"""
List of constants used in intent parser's Google App Script Add-on
"""
ACTION_UPDATE_PROGRESS = 'updateProgress'

ANALYZE_CONTENT_TERM = 'content_term'
ANALYZE_END_OFFSET = 'end_offset'
ANALYZE_LINK = 'link'
ANALYZE_NEVER_LINK = 'process_never_link'
ANALYZE_NO = 'process_analyze_no'
ANALYZE_NO_TO_ALL = 'process_no_to_all'
ANALYZE_PARAGRAPH_INDEX = 'paragraph_index'
ANALYZE_PROGRESS = 'progress'
ANALYZE_OFFSET = 'offset'
ANALYZE_TERM = 'term'
ANALYZE_YES = 'process_analyze_yes'
ANALYZE_YES_TO_ALL = 'process_link_all'
BUTTON_ID = 'buttonId'
CHILD_INDEX = 'childIndex'
CURSOR_CHILD_INDEX = 'cursorChildIndex'
DOCUMENT_ID = 'documentId'

HTML_BATCH = 'batch'
HTML_CAPTION = 'caption'
HTML_CHANNEL = 'channel'
HTML_CONTENT = 'content'
HTML_CONTROLS = 'controls'
HTML_CONTROL_TYPES = 'controlTypes'
HTML_FILE_TYPES = 'fileTypes'
HTML_LAB = 'lab'
HTML_MEASUREMENT_TYPES = 'measurementTypes'
HTML_NOTES = 'notes'
HTML_NUM_OF_REAGENTS = 'numReagents'
HTML_REAGENT_TIMEPOINT_VALUE = 'reagentTimepointValue'
HTML_REAGENT_TIMEPOINT_UNIT = 'reagentTimepointUnit'
HTML_NUM_OF_ROW = 'numRows'
HTML_ODS = 'ods'
HTML_PROTOCOL = 'protocol'
HTML_TEMPERATURE = 'temperature'
HTML_TIMEPOINT = 'timepoint'

TABLE_DATA = 'tableData'
TABLE_TYPE = 'tableType'
TABLE_TYPE_CONTROLS = 'controls'
TABLE_TYPE_EXPERIMENT_SPECIFICATION = 'experimentSpecification'
TABLE_TYPE_STATUS = 'tableStatus'
TABLE_TYPE_LAB = 'tableLab'
TABLE_TYPE_MEASUREMENTS = 'measurements'
TABLE_TYPE_PARAMETERS = 'parameters'

