"""
List of constants used for referring to terms in SD2's datacatalog schema.
"""
CHALLENGE_PROBLEM = 'challenge_problem'
CHANNEL = 'channel'
CONTENTS = 'contents'
DEFAULT_PARMETERS = 'default_parameters'
DOCUMENT_REVISION_ID = 'doc_revision_id'
EXPERIMENT_REQUEST_NAME = 'name'
EXPERIMENT_ID = 'experiment_id'
EXPERIMENT_REFERENCE = 'experiment_reference'
EXPERIMENT_REFERENCE_URL = 'experiment_reference_url'
EXPERIMENT_VERSION = 'experiment_version'
LAB = 'lab'
LABEL = 'label'
NAME = 'name'
PARAMETERS = 'parameters'
RUNS = 'runs'
SBH_URI = 'sbh_uri'
STATUS_ELEMENT = 'status_element'
STRAINS = 'strains'
TIMEPOINTS = 'timepoints'
TYPE = 'type'
VALUE = 'value'
UNIT = 'unit'