"""
List of constants used for referring to terms in SD2's datacatalog schema.
"""
BATCH = 'batch'
CHALLENGE_PROBLEM = 'challenge_problem'
CHANNEL = 'channel'
CONTENTS = 'contents'
CONTROLS = 'controls'
DEFAULT_PARMETERS = 'default_parameters'
DOCUMENT_REVISION_ID = 'doc_revision_id'
EXPERIMENT_REQUEST_NAME = 'name'
EXPERIMENT_ID = 'experiment_id'
EXPERIMENT_REFERENCE = 'experiment_reference'
EXPERIMENT_REFERENCE_URL = 'experiment_reference_url'
EXPERIMENT_VERSION = 'experiment_version'
FILE_TYPE ='file_type'
LAB = 'lab'
LABEL = 'label'
MEASUREMENT_TYPE = 'measurement_type'
NAME = 'name'
NO_PROGRAM_DICTIONARY = 'NO PROGRAM DICTIONARY ENTRY'
ODS = 'ods'
PARAMETERS = 'parameters'
REPLICATES = 'replicates'
RUNS = 'runs'
SBH_URI = 'sbh_uri'
STATUS_ELEMENT = 'status_element'
STRAINS = 'strains'
TEMPERATURES = 'temperatures'
TIMEPOINT = 'timepoint'
TIMEPOINTS = 'timepoints'
TYPE = 'type'
VALUE = 'value'
UNDEFINED = 'UNDEFINED'
UNKOWN = 'Unknown'
UNIT = 'unit'