"""
List of constants used for referring to terms in SD2's datacatalog schema.
"""
BATCH = 'batch'
CHALLENGE_PROBLEM = 'challenge_problem'
CHANNEL = 'channel'
CONTENTS = 'contents'
CONTROLS = 'controls'
DEFAULT_PARMETERS = 'default_parameters'
DOCUMENT_REVISION_ID = 'doc_revision_id'
EXPERIMENT_REQUEST_NAME = 'name'
EXPERIMENT_ID = 'experiment_id'
EXPERIMENT_REFERENCE = 'experiment_reference'
EXPERIMENT_REFERENCE_URL = 'experiment_reference_url'
EXPERIMENT_VERSION = 'experiment_version'
FILE_TYPE ='file_type'

LAB = 'lab'
LAB_CALTECH = 'Caltech'
LAB_DUKE_HAASE = 'Duke_Haase'
LAB_EMERALD = 'Emerald'
LAB_GEO = 'GEO'
LAB_GINKGO = 'Ginkgo'
LAB_MARSHALL = 'Marshall'
LAB_PNNL_EGBERT = 'PNNL_Egbert'
LAB_PSU_SALIS = 'PSU_Salis'
LAB_TACC = 'TACC'
LAB_TRANSCRIPTIC  = 'Transcriptic'
LAB_UCSB_YEUNG = 'UCSB_Yeung'
LAB_UW_BIOFAB = 'UW_BIOFAB'

LAB_ID = 'lab_id'
LABEL = 'label'
MEASUREMENTS = 'measurements'
MEASUREMENT_TYPE = 'measurement_type'
NAME = 'name'
NO_PROGRAM_DICTIONARY = 'NO PROGRAM DICTIONARY ENTRY'
ODS = 'ods'
PARAMETERS = 'parameters'
REPLICATES = 'replicates'
RUNS = 'runs'
SBH_URI = 'sbh_uri'
STATUS_ELEMENT = 'status_element'
STRAINS = 'strains'
TEMPERATURES = 'temperatures'
TIMEPOINT = 'timepoint'
TIMEPOINTS = 'timepoints'
TYPE = 'type'
VALUE = 'value'
UNDEFINED = 'UNDEFINED'
UNKOWN = 'Unknown'
UNIT = 'unit'