XPLAN_REQUEST_SUBMITTED = 'xplan_request_submitted'
ANNOTATED = 'annotated'
COMPARISON_PASSED = 'comparison_passed'
CONVERTED = 'converted'
INGESTED = 'ingested'
MTYPES = 'mtypes'
OBS_LOAD = 'obs_load'
UPLOADED = 'uploaded'

EXPERIMENT_ID = 'experiment_id'
EXPERIMENT_REFERENCE_URL = 'experiment_reference_url'
LAB = 'lab'
LAST_UPDATED = 'last_updated'
PARENT_GIT_PATH = 'parent_git_path'
PATH = 'path'
STATE = 'state'
STATUS = 'status'
